-- HEIC 轉檔與 MOV 關鍵影格只存放在私有 Storage bucket。
insert into storage.buckets (id, name, public, file_size_limit)
values ('costco-onsite-media', 'costco-onsite-media', false, 52428800)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit;

create table if not exists public.costco_photo_media_assets (
  id bigint generated by default as identity primary key,
  photo_id text not null references public.costco_photo_processing_queue(id) on delete cascade,
  asset_type text not null check (asset_type in ('JPEG', 'KEY_FRAME')),
  frame_number integer not null default 0,
  storage_bucket text not null default 'costco-onsite-media',
  storage_path text not null,
  mime_type text not null,
  byte_size bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (photo_id, asset_type, frame_number),
  unique (storage_bucket, storage_path)
);

create index if not exists idx_costco_media_assets_photo
  on public.costco_photo_media_assets(photo_id, asset_type, frame_number);

alter table public.costco_photo_media_assets enable row level security;

-- 不建立 anon/authenticated policy；Queue 與衍生檔只供 service_role／後台處理。
