-- Vision 只寫入候選資料；人工確認後才可進入 VERIFIED／published。
create table if not exists public.costco_vision_candidates (
  id bigint generated by default as identity primary key,
  photo_id text not null references public.costco_photo_processing_queue(id) on delete cascade,
  asset_id bigint references public.costco_photo_media_assets(id) on delete set null,
  model text,
  raw_result jsonb not null default '{}'::jsonb,
  product_name text,
  brand text,
  costco_item_number text,
  jan text,
  package_quantity numeric,
  package_unit text,
  observed_price_jpy numeric,
  regular_price_jpy numeric,
  sale_price_jpy numeric,
  sale_evidence text,
  sale_end_date date,
  confidence numeric,
  status text not null default 'CANDIDATE'
    check (status in ('CANDIDATE', 'NEEDS_RECHECK', 'VERIFIED', 'REJECTED')),
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_costco_vision_candidates_review
  on public.costco_vision_candidates(status, created_at);

create table if not exists public.costco_photo_pairings (
  id bigint generated by default as identity primary key,
  product_photo_id text not null references public.costco_photo_processing_queue(id) on delete cascade,
  price_tag_photo_id text references public.costco_photo_processing_queue(id) on delete set null,
  method text not null default 'candidate',
  score numeric,
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'NEEDS_REVIEW'
    check (status in ('CANDIDATE', 'NEEDS_REVIEW', 'VERIFIED', 'REJECTED')),
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_photo_id, price_tag_photo_id)
);

create index if not exists idx_costco_pairings_review
  on public.costco_photo_pairings(status, score desc);

alter table public.costco_vision_candidates enable row level security;
alter table public.costco_photo_pairings enable row level security;

-- 這兩張表不建立 anon/authenticated policy；候選結果只供 service_role／後台。
